name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Test Python imports
      run: |
        python -c "import sys; print('Python version:', sys.version)"
        python -c "import tkinter; print('Tkinter available')"
        python -c "import tkcalendar; print('tkcalendar version:', tkcalendar.__version__)"
        python -c "import tkcalendar.calendar_; print('tkcalendar.calendar_ available')"
        python -c "import tkcalendar.dateentry; print('tkcalendar.dateentry available')"
        python -c "import tkcalendar.tooltip; print('tkcalendar.tooltip available')"
        python -c "import tkcalendar.__main__; print('tkcalendar.__main__ available')"
        python -c "import babel; print('babel available')"
        python -c "import babel.dates; print('babel.dates available')"
        python -c "from tkcalendar import DateEntry, Calendar; print('tkcalendar DateEntry and Calendar imports successful')"
        python -c "import PIL; print('PIL available')"
        python -c "import docx; print('python-docx available')"
        python -c "import sys, os; sys.path.insert(0, os.path.join(os.getcwd(), 'src')); from src.core.main_app import OfferGeneratorMainApp; print('Main app import successful')"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        echo "Current pip version:"
        pip --version
        echo "Python version:"
        python --version
        echo "Contents of requirements.txt:"
        type requirements.txt
        echo "Installing requirements from requirements.txt..."
        pip install -r requirements.txt || echo "requirements.txt failed, trying individual packages..."
        echo "Installing critical packages individually..."
        pip install python-docx>=0.8.11
        pip install Pillow>=8.0.0
        pip install PyInstaller>=5.0.0
        pip install tkcalendar>=1.6.0
        pip install babel>=2.9.0
        pip install docxcompose>=1.4.0
        echo "Final pip list:"
        pip list
        echo "Verifying final installations..."
        pip show tkcalendar
        pip show babel
        pip show Pillow
        pip show python-docx
    
    - name: Build executable (with console for debugging)
      run: |
        python -m PyInstaller --clean --onefile --console --name=OfferGenerator-Debug --additional-hooks-dir=. --add-data="templates/*;templates" --add-data="background_offer_1.png;." --add-data="app_settings.json;." --hidden-import=PIL._tkinter_finder --hidden-import=PIL.Image --hidden-import=docx --hidden-import=docx.shared --hidden-import=docx.enum.text --hidden-import=docx.enum.table --hidden-import=tkcalendar --hidden-import=tkcalendar.calendar_ --hidden-import=tkcalendar.dateentry --hidden-import=tkcalendar.tooltip --hidden-import=tkcalendar.__main__ --hidden-import=babel --hidden-import=babel.dates --hidden-import=src.core.main_app --hidden-import=src.core.navigation_manager --hidden-import=src.core.offer_generator_app --hidden-import=src.core.offer_editor_app --hidden-import=src.ui.frames.main_menu_frame --hidden-import=src.ui.frames.settings_frame --hidden-import=src.ui.frames.browse_clients_frame --hidden-import=src.ui.frames.browse_suppliers_frame --hidden-import=src.ui.frames.browse_offers_frame --hidden-import=src.ui.frames.offer_creation_frame --hidden-import=src.ui.frames.offer_editor_frame --hidden-import=src.ui.components.ui_components --hidden-import=src.ui.components.product_table --hidden-import=src.ui.windows.client_search_window --hidden-import=src.ui.windows.supplier_search_window --hidden-import=src.ui.windows.product_add_window --hidden-import=src.ui.windows.product_edit_window --hidden-import=src.services.offer_generator_service --hidden-import=src.services.offer_editor_service --hidden-import=src.services.sync_service --hidden-import=src.data.database_service --hidden-import=src.utils.config --hidden-import=src.utils.settings main.py
    
    - name: Build executable (without console - final version)
      run: |
        python -m PyInstaller --clean --onefile --noconsole --name=OfferGenerator --additional-hooks-dir=. --add-data="templates/*;templates" --add-data="background_offer_1.png;." --add-data="app_settings.json;." --hidden-import=PIL._tkinter_finder --hidden-import=PIL.Image --hidden-import=docx --hidden-import=docx.shared --hidden-import=docx.enum.text --hidden-import=docx.enum.table --hidden-import=tkcalendar --hidden-import=tkcalendar.calendar_ --hidden-import=tkcalendar.dateentry --hidden-import=tkcalendar.tooltip --hidden-import=tkcalendar.__main__ --hidden-import=babel --hidden-import=babel.dates --hidden-import=src.core.main_app --hidden-import=src.core.navigation_manager --hidden-import=src.core.offer_generator_app --hidden-import=src.core.offer_editor_app --hidden-import=src.ui.frames.main_menu_frame --hidden-import=src.ui.frames.settings_frame --hidden-import=src.ui.frames.browse_clients_frame --hidden-import=src.ui.frames.browse_suppliers_frame --hidden-import=src.ui.frames.browse_offers_frame --hidden-import=src.ui.frames.offer_creation_frame --hidden-import=src.ui.frames.offer_editor_frame --hidden-import=src.ui.components.ui_components --hidden-import=src.ui.components.product_table --hidden-import=src.ui.windows.client_search_window --hidden-import=src.ui.windows.supplier_search_window --hidden-import=src.ui.windows.product_add_window --hidden-import=src.ui.windows.product_edit_window --hidden-import=src.services.offer_generator_service --hidden-import=src.services.offer_editor_service --hidden-import=src.services.sync_service --hidden-import=src.data.database_service --hidden-import=src.utils.config --hidden-import=src.utils.settings main.py
    
    - name: Upload executable (Debug version)
      uses: actions/upload-artifact@v4
      with:
        name: OfferGenerator-Windows-Debug
        path: dist/OfferGenerator-Debug.exe
    
    - name: Upload executable (Final version)
      uses: actions/upload-artifact@v4
      with:
        name: OfferGenerator-Windows
        path: dist/OfferGenerator.exe
    
    - name: Create distribution package
      run: |
        mkdir distribution_windows
        copy dist\OfferGenerator.exe distribution_windows\
        copy app_settings.json distribution_windows\
        copy background_offer_1.png distribution_windows\
        xcopy /E /I templates distribution_windows\templates
        echo "# Generator Ofert - Windows" > distribution_windows\README.txt
        echo "" >> distribution_windows\README.txt
        echo "Uruchom OfferGenerator.exe aby rozpoczac" >> distribution_windows\README.txt
    
    - name: Create ZIP package
      run: |
        powershell Compress-Archive -Path distribution_windows\* -DestinationPath OfferGenerator-Windows.zip
    
    - name: Upload distribution
      uses: actions/upload-artifact@v4
      with:
        name: OfferGenerator-Windows-Complete
        path: OfferGenerator-Windows.zip
